/* Auto-generated by cbindgen — do not edit. */

#ifndef ALLOY_TEXT_H
#define ALLOY_TEXT_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque buffer handle.
 */
typedef uint64_t AlloyBufferId;

/**
 * A heap-allocated byte slice handed back to Swift. The caller owns it and must
 * return it via [`alloy_slice_free`]. `cap` is carried so we can reconstruct the
 * original `Vec` for deallocation.
 */
typedef struct AlloySlice {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t cap;
} AlloySlice;

/**
 * Create a buffer from initial UTF-8 bytes. Pass `null`/`0` for an empty buffer.
 * Returns 0 on failure.
 */
AlloyBufferId alloy_buffer_create(const uint8_t *bytes, uintptr_t len);

/**
 * Destroy a buffer and free its memory.
 */
void alloy_buffer_destroy(AlloyBufferId id);

/**
 * Replace the bytes in `[byte_start, byte_start + old_byte_len)` with `new_bytes`.
 * This is the single hot-path mutation: one call per keystroke / paste / delete.
 */
void alloy_buffer_edit(AlloyBufferId id,
                       uintptr_t byte_start,
                       uintptr_t old_byte_len,
                       const uint8_t *new_bytes,
                       uintptr_t new_len);

/**
 * Total length in UTF-8 bytes.
 */
uintptr_t alloy_buffer_len_bytes(AlloyBufferId id);

/**
 * Number of lines. A trailing newline yields a final empty line (ropey semantics),
 * matching how editors present a file that ends in `\n`.
 */
uintptr_t alloy_buffer_line_count(AlloyBufferId id);

/**
 * The content of `line_index` *excluding* its trailing line break.
 * Returns an empty slice for out-of-range indices. Caller frees with `alloy_slice_free`.
 */
struct AlloySlice alloy_buffer_line(AlloyBufferId id, uintptr_t line_index);

/**
 * The byte length of `line_index` excluding its trailing line break.
 */
uintptr_t alloy_buffer_line_len_bytes(AlloyBufferId id, uintptr_t line_index);

/**
 * The entire buffer as UTF-8 bytes. Caller frees with `alloy_slice_free`.
 */
struct AlloySlice alloy_buffer_text(AlloyBufferId id);

/**
 * Byte offset of the first character of `line_index`.
 */
uintptr_t alloy_buffer_line_to_byte(AlloyBufferId id, uintptr_t line_index);

/**
 * Line index containing `byte_offset`.
 */
uintptr_t alloy_buffer_byte_to_line(AlloyBufferId id, uintptr_t byte_offset);

/**
 * Free a slice previously returned by this library.
 */
void alloy_slice_free(struct AlloySlice slice);

#endif  /* ALLOY_TEXT_H */
